### ISSUE TITLE
[1.10.2] Server crash - Tinkers tool in progressive automation

### ISSUE THREAD

**Issue by ProsperCraft** [SlimeKnights/TinkersToolLeveling#9]
http://pastebin.com/Zdnkmchy

Description: Ticking block entity
 
java.lang.NullPointerException: Ticking block entity
    at slimeknights.tconstruct.common.Sounds.PlaySoundForPlayer(Sounds.java:46)
    at slimeknights.toolleveling.CommonProxy.playLevelupDing(CommonProxy.java:19)
    at slimeknights.toolleveling.ModToolLeveling.addXp(ModToolLeveling.java:121)
    at slimeknights.toolleveling.ModToolLeveling.afterBlockBreak(ModToolLeveling.java:64)
    at slimeknights.tconstruct.library.tools.ToolCore.afterBlockBreak(ToolCore.java:513)
    at slimeknights.tconstruct.tools.tools.Hatchet.afterBlockBreak(Hatchet.java:86)
    at slimeknights.tconstruct.library.tools.ToolCore.func_179218_a(ToolCore.java:503)
    at slimeknights.tconstruct.library.tools.TinkerToolCore.func_179218_a(TinkerToolCore.java:51)
    at com.vanhal.progressiveautomation.ref.ToolHelper.damageTool(ToolHelper.java:212)
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.cutTree(TileChopper.java:250)
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.func_73660_a(TileChopper.java:173)
    at net.minecraft.world.World.func_72939_s(World.java:1804)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

**Comment by ProsperCraft** [comment]
Here is another example
http://pastebin.com/TrGDXGMr

Modpack - Allthemods 1.33

**Comment by bonii-xx** [comment]
Hm yeah. I guess fake players don't have a connection. Technically a TiC bug

**Comment by DietmarKrause** [comment]
Note: crashes Single player worlds too.  Reported for "all the mods" modpack.

**Comment by bonii-xx** [comment]
Should be fixed in TiC 2.5.6
